"""สร้างโครงสร้างตารางระบบคลังพัสดุแรกเริ่ม

Revision ID: 76fd2013a152
Revises: 
Create Date: 2026-05-22 15:44:31.863429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76fd2013a152'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🎯 1. ประกาศสร้าง Custom Enum Types ลงในฐานข้อมูล PostgreSQL ก่อนเริ่มปรับโครงสร้างคอลัมน์
    history_action_enum = postgresql.ENUM('IN', 'OUT', 'RESERVE', 'ADJUST', name='history_action_enum')
    history_action_enum.create(op.get_bind(), checkfirst=True)

    reserved_status_enum = postgresql.ENUM('RESERVED', 'APPROVED', 'RELEASED', 'ISSUED', 'CANCELLED', name='reserved_status_enum')
    reserved_status_enum.create(op.get_bind(), checkfirst=True)

    issue_status_enum = postgresql.ENUM('ISSUED', 'CANCELLED', name='issue_status_enum')
    issue_status_enum.create(op.get_bind(), checkfirst=True)

    role_enum = postgresql.ENUM('User', 'Admin', 'BranchManager', name='role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)

    # 🎯 2. ปรับปรุงคอลัมน์เดิมโดยเพิ่มกลไก USING เพื่อหล่อหลอมแปลงชนิดข้อมูลโดยอัตโนมัติ
    op.alter_column('material_history', 'action_type',
               existing_type=sa.VARCHAR(length=10),
               type_=history_action_enum,
               existing_nullable=False,
               postgresql_using='action_type::history_action_enum')
    
    op.create_index(op.f('ix_material_history_history_id'), 'material_history', ['history_id'], unique=False)
    op.create_foreign_key(None, 'material_history', 'sams_material', ['mat_id'], ['mat_id'])
    
    op.alter_column('material_issue', 'issued_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('material_issue', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    
    op.alter_column('material_issue', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=issue_status_enum,
               nullable=False,
               postgresql_using='status::issue_status_enum')
    
    op.alter_column('material_issue', 'mat_req_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    op.create_index(op.f('ix_material_issue_issue_id'), 'material_issue', ['issue_id'], unique=False)
    op.drop_constraint(op.f('fk_issue_material'), 'material_issue', type_='foreignkey')
    
    op.alter_column('material_req', 'mat_req_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('material_req', 'user_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('material_req', 'req_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'ISSUED', name='req_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::req_status_enum"))
    
    # ดักดึงค่า Enum เก่ามาปรับโครงสร้างหากจำเป็น (กรณีต้องการล้างรอยต่อตัวแปร req_status)
    op.create_index(op.f('ix_material_req_mat_req_id'), 'material_req', ['mat_req_id'], unique=False)
    op.create_unique_constraint(None, 'material_req', ['mat_req_code'])
    op.create_foreign_key(None, 'material_req', 'sams_users', ['user_id'], ['emp_code'])
    
    op.alter_column('material_req_detail', 'mat_req_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('material_req_detail', 'mat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('material_req_detail', 'req_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    op.create_index(op.f('ix_material_req_detail_detail_id'), 'material_req_detail', ['detail_id'], unique=False)
    
    op.alter_column('material_reserved', 'req_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('material_reserved', 'status',
               existing_type=sa.TEXT(),
               type_=reserved_status_enum,
               existing_nullable=False,
               postgresql_using='status::reserved_status_enum')
    
    op.create_index(op.f('ix_material_reserved_reserve_id'), 'material_reserved', ['reserve_id'], unique=False)
    op.create_foreign_key(None, 'material_reserved', 'sams_material', ['mat_id'], ['mat_id'])
    op.create_foreign_key(None, 'material_reserved', 'material_req', ['req_id'], ['mat_req_id'])
    
    op.alter_column('material_stock', 'mat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_material_stock_mat'), 'material_stock', type_='unique')
    op.drop_constraint(op.f('fk_stock_material'), 'material_stock', type_='foreignkey')
    
    op.alter_column('material_type', 'mat_type_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sams_branch', 'branch_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sams_material', 'mat_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    
    op.alter_column('sams_material', 'price_per_pack',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    
    op.alter_column('sams_service', 'branch_id',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('sams_service', 'service_point_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    
    op.alter_column('sams_users', 'user_role',
               existing_type=postgresql.ENUM('Admin', 'User', 'BranchManager', name='user_role_enum'),
               type_=role_enum,
               nullable=True,
               existing_server_default=sa.text("'User'::user_role_enum"),
               postgresql_using='user_role::text::role_enum')
    
    op.alter_column('sams_users', 'profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sams_users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    
    op.drop_constraint(op.f('uq_emp_code'), 'sams_users', type_='unique')
    op.create_index(op.f('ix_sams_users_emp_code'), 'sams_users', ['emp_code'], unique=True)
    op.create_index(op.f('ix_sams_users_user_id'), 'sams_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sams_users_user_id'), table_name='sams_users')
    op.drop_index(op.f('ix_sams_users_emp_code'), table_name='sams_users')
    op.create_unique_constraint(op.f('uq_emp_code'), 'sams_users', ['emp_code'])
    
    op.alter_column('sams_users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sams_users', 'profile_image',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sams_users', 'user_role',
               existing_type=sa.Enum('User', 'Admin', 'BranchManager', name='role_enum'),
               type_=postgresql.ENUM('Admin', 'User', 'BranchManager', name='user_role_enum'),
               nullable=False,
               existing_server_default=sa.text("'User'::user_role_enum"))
    
    op.alter_column('sams_service', 'service_point_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sams_service', 'branch_id',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    
    op.alter_column('sams_material', 'price_per_pack',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('sams_material', 'mat_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sams_branch', 'branch_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('material_type', 'mat_type_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    
    op.create_foreign_key(op.f('fk_stock_material'), 'material_stock', 'sams_material', ['mat_id'], ['mat_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_material_stock_mat'), 'material_stock', ['mat_id'])
    
    op.alter_column('material_stock', 'mat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    op.drop_constraint(None, 'material_reserved', type_='foreignkey')
    op.drop_constraint(None, 'material_reserved', type_='foreignkey')
    
    op.drop_index(op.f('ix_material_reserved_reserve_id'), table_name='material_reserved')
    op.alter_column('material_reserved', 'status',
               existing_type=sa.Enum('RESERVED', 'APPROVED', 'RELEASED', 'ISSUED', 'CANCELLED', name='reserved_status_enum'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('material_reserved', 'req_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    op.drop_index(op.f('ix_material_req_detail_detail_id'), table_name='material_req_detail')
    op.alter_column('material_req_detail', 'req_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('material_req_detail', 'mat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('material_req_detail', 'mat_req_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    op.drop_constraint(None, 'material_req', type_='foreignkey')
    op.drop_constraint(None, 'material_req', type_='unique')
    
    op.drop_index(op.f('ix_material_req_mat_req_id'), table_name='material_req')
    op.alter_column('material_req', 'req_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'ISSUED', name='req_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::req_status_enum"))
    op.alter_column('material_req', 'user_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('material_req', 'mat_req_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    
    op.create_foreign_key(op.f('fk_issue_material'), 'material_issue', 'sams_material', ['mat_id'], ['mat_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_material_issue_issue_id'), table_name='material_issue')
    
    op.alter_column('material_issue', 'mat_req_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('material_issue', 'status',
               existing_type=sa.Enum('ISSUED', 'CANCELLED', name='issue_status_enum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('material_issue', 'note',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('material_issue', 'issued_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    op.drop_constraint(None, 'material_history', type_='foreignkey')
    op.drop_index(op.f('ix_material_history_history_id'), table_name='material_history')
    op.alter_column('material_history', 'action_type',
               existing_type=sa.Enum('IN', 'OUT', 'RESERVE', 'ADJUST', name='history_action_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    
    # 🎯 3. สั่งล้างข้อมูลชนิดพิเศษ Enum ออกจากระบบตอนสั่งทำ Downgrade ถอยหลังกลับ
    postgresql.ENUM(name='history_action_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='reserved_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='issue_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='role_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###